<?php
/**
 *
 * Descrição: Menu montado de acordo com o perfil do usuário logado.
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 20-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex2-collapse">
            <span class="sr-only">Alterar Navega&ccedil;&atilde;o</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse navbar-ex2-collapse">
        <?php foreach ($this->itensMenu as $vMenuItem) : ?>
        <button type="button" class="btn <?php print $vMenuItem['class_botao'] ?> navbar-btn" id="<?php print $vMenuItem['id_action'] ?>" rel="<?php print $this->url(array('controller' =>$vMenuItem['rel_controller'],'action'=>$vMenuItem['rel_action']))?>" title="<?php print $vMenuItem['descricao_action'] ?>"><i class="<?php print $vMenuItem['class_icone'] ?>"></i> <?php print $vMenuItem['nome_action'] ?></button>
        <?php endforeach;?>
    </div>
</nav>