<?php
/**
 *
 * Descrição: Menu montado de acordo com o perfil do usuário logado.
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 20-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex2-collapse">
            <span class="sr-only">Alterar Navega&ccedil;&atilde;o</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse navbar-ex2-collapse">
        <button type="button" class="btn btn-default navbar-btn" id="salvar"><i class="icon-save"></i> Salvar</button>
        <button type="button" class="btn btn-default navbar-btn" id="excluir"><i class="icon-remove"></i> Excluir</button>
        <button type="button" class="btn btn-default navbar-btn" id="imprimir"><i class="icon-print"></i> Imprimir</button>
    </div>
</nav>