<?php
/**
 *
 * Descrição:View navigation
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 20-Aug-2013
 *
 * @version 1.0.0
 *
 */
$vController     = array();
$vControllerDesc = array();
foreach ($this->itensMenu as $value) {
    $vController[$value['controller']]     = $value['controller'];
    $vControllerDesc[$value['controller']] = $value['descricao_action'];
}
$vMenu     = array();
$vMenuDesc = array();
foreach ($this->itensMenu as $value) {
    $vMenu[$vController[$value['controller']]][$value['codigo_controller']][$value['action']] = $value['id_action'];
    $vMenuDesc[$vController[$value['controller']]] = $value['descricao_controller'];
}
?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Alterar Navega&ccedil;&atilde;o</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php print $this->url(array('controller' => 'index', 'action' => 'index')) ?>">Grass</a>
        </div>
        <div class="collapse navbar-collapse bs-js-navbar-collapse">
            <ul class="nav navbar-nav">
                <?php foreach ($vMenu as $modulo => $controllers) : ?>
                        <li class="dropdown">
                            <a id="drop1" href="#" role="button" class="dropdown-toggle" title="<?php print $vMenuDesc[$modulo] ?>" data-toggle="dropdown"><?php print $modulo;?> <b class="caret"></b></a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="drop1">
                            <?php foreach ($controllers as $action => $itensActions) : ?>
                                <?php foreach ($itensActions as $item => $link ) : ?>
                                <li role="presentation"><a role="menuitem" tabindex="-1" title="<?php print $vControllerDesc[$action] ?>" href="<?php print $this->url(array('controller' => strtolower($action), 'action' => strtolower($link)))?>"><?php print $item;?></a></li>
                                <?php endforeach;?>
                            <?php endforeach;?>
                        </ul>
                    </li>
                <?php endforeach;?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li id="fat-menu" class="dropdown">
                    <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown" title="Ajuda"><i class="icon-question-sign"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li role="presentation"><a role="menuitem" tabindex="-1" id="btMenuSobre" title="Sobre o sistema" href="<?php print $this->url(array('controller' => 'ajuda', 'action' => 'sobre')) ?>">Sobre</a></li>
                    </ul>
                </li>
                <li class="fat-menu">
                    <form class="navbar-form navbar-right" action="<?php print $this->url(array('controller' => 'auth', 'action' => 'logout')) ?>">
                        <button type="submit" class="btn btn-success" title="Sair do sistema com seguran&ccedil;a">Sair com seguran&ccedil;a&nbsp;&nbsp;<i class="icon-off"></i></button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</div>
