<?php
/**
 *
 * Descrição: Menu montado de acordo com o perfil do usuário logado.
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 20-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<div class="btn-group pull-right">
    <button type="button" class="btn btn-default btn-lg">
        Salvar&nbsp;&nbsp;<i class="icon-save"></i>
    </button>
    <button type="button" class="btn btn-default btn-lg">
        Editar&nbsp;&nbsp;<i class="icon-edit"></i>
    </button>
    <button type="button" class="btn btn-default btn-lg">
        Excluir&nbsp;&nbsp;<i class="icon-trash"></i>
    </button>
</div>