<?php
/**
 *
 * Descrição:cad-pessoa-fisica
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 21-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<div class="panel panel-default">
    <div class="panel-heading">Cadastro de pessoa fisica</div>
    <div class="panel-body">
        <div class="row-fluid">
            <div class="bs-example bs-example-tabs">
                <ul id="myTab" class="nav nav-tabs">
                    <li class="active"><a href="#home" data-toggle="tab">Cadastro</a></li>
                    <li><a href="#endereco" data-toggle="tab">Endere&ccedil;o</a></li>
                    <li><a href="#usuario" data-toggle="tab">Usu&aacute;rio do sistema</a></li>
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="home">
                        <form action="">
                            <div class="control-group">
                                <label for="cpf" class="control-label">Cpf</label>
                                <div class="controls">
                                    <input type="text" name="cpf" id="cpf" class="" value="" />
                                </div>
                            </div>
                            <div class="control-group">
                                <label for="nome" class="control-label">Nome</label>
                                <div class="controls">
                                    <input type="text" name="nome" id="nome" class="" value="" />
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="tab-pane fade" id="endereco">
                        
                    </div>
                    <div class="tab-pane fade" id="usuario">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>