<?php
/**
 * Formulário de login
 */
$this->title = 'Login';
$this->headTitle($this->title);

/*
 * Identificando o usuário logado
 */
// $sessao = Zend_Auth::getInstance();
// if(empty($sessao->getIdentity()->cd_usuario)){
//     $this->_redirect('/auth/login');
// }
?>
<?php if(sizeof( $this->messages ) > 0) : ?>
<div class="alert alert-error">
    <?php echo $this->messages[0]?>
</div>
<?php endif;?>
<div class="row-fluid">
    <div class="span4">
          <form name="form" id="editoras" enctype="application/x-www-form-urlencoded" action="<?php echo $this->url(array('controller' => 'auth','action' => 'login')); ?>" method="post">
            <label for="login">Login</label>
            <input type="text" name="login" id="login" class="input-form login-fields" autocomplete="off" />
            <div class="form-validation" id="loginValid">* Campo <b>Login</b> inv&aacute;lido!</div>
            <label for="senha">Senha</label>
            <input type="password" name="senha" id="senha" class="input-form login-fields" autocomplete="off" />
            <div class="form-validation" id="senhaValid">* Campo <b>Senha</b> inv&aacute;lido!</div>
            <br />
             <input type="button" name="cadastrar" id="btLogar" value="Logar" class="btn btn-primary pull-right">
        </form>
    </div>
    <div class="span8">
        <table border="0" width="100%">
            <tr>
                <td align="center" valign="center">
                    <img src="<?php print $this->baseUrl() . '/img/login.jpg'?>" />
                </td>
            </tr>
        </table>
    </div>
</div>