<?php
/**
 * @author Fabricio Nogueira
 */
?>
<!DOCTYPE html>
    <!--[if lt IE 7]>
          <html class="no-js lt-ie9 lt-ie8 lt-ie7"> 
    <![endif]-->
    <!--[if IE 7]>
         <html class="no-js lt-ie9 lt-ie8"> 
     <![endif]-->
    <!--[if IE 8]> 
        <html class="no-js lt-ie9"> 
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <html class="no-js"> 
    <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <?php echo $this->defaults() ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <meta name="viewport" content="width=device-width">
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.min.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap-theme.min.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/font-awesome.min.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/default.css'); ?>
        <?php echo $this->headLink() ?>
    </head>
    <body>
        <?php if (!empty($this->usuario())) : ?>
            <?php echo $this->layout()->navigation; ?>
         <?php else : ?>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Grass</a>
                </div>
                <div class="collapse navbar-collapse">
                </div>
            </div>
        </div>
        <?php endif;?>
        <div class="container">
            <div id="content">
                <div class="row">
                    <div class="col-md-pull-12">
                        <span class="pull-right"><p class="text-muted"><?php print $this->usuario();?></p></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-pull-12">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>
            </div>        
            <hr>
        </div>
        <footer>
            <div class="container">
                <div id="content">
                    <p>&copy; Grass <?php echo date('Y')?> <span class="pull-right">Desenvolvido por: <a href="http://www.nogsantos.com.br" target="_blank">Fabricio Nogueira</a></span> </p>
                </div>
            </div>
        </footer>
        <script type="text/javascript" src="<?php print $this->baseUrl('/js/jquery-1.10.2.min.js')?>"></script>
        <script type="text/javascript" src="<?php print $this->baseUrl('/js/bootstrap.min.js')?>"></script>
        <script type="text/javascript" src="<?php print $this->baseUrl('/js/bootbox.js')?>"></script>
        <script type="text/javascript" src="<?php print $this->baseUrl('/js/layout.js')?>"></script>
        <?php echo $this->headScript() ?>
    </body>
</html>

