<?php
/**
 * @author Fabricio Nogueira
 */
$vOrganizacao = $this->organizacaoDefault()->toViewSingle();
?>
<!DOCTYPE html>
<html lang="pt_BR">
    <head>
        <meta charset="utf-8">
        <?php print $this->defaults() ?>
        <?php print $this->headTitle(); ?>
        <?php print $this->headMeta(); ?>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Fabricio Nogueira">
        <?php print $this->headLink() ?>
        <script type="text/javascript">
            var baseUrl = '<?php print $this->baseUrl(); ?>';
        </script>
    </head>
    <body>
        <?php $usuario = $this->usuario();?>
        <?php if (!empty($usuario)) : ?>
            <?php print $this->layout()->navigation; ?>
         <?php else : ?>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#"><?php print $this->sistema ?></a>
                </div>
            </div>
        </div>
        <?php endif;?>
        <div class="container-fluid">
            <div id="content">
                <div class="row">
                    <div class="col-md-pull-12">
                        <?php print $this->layout()->content; ?>
                    </div>
                </div>
            </div>        
            <hr>
        </div>
        <footer>
            <div class="container-fluid">
                <div id="content">
                    <div class="col-md-4 pull-left">&copy; <?php print $this->sistema ?> <?php print date('Y')?></div>
                    <div class="col-md-4 pull-right text-right"><?php print $this->usuario();?></div>
                    <div class="col-md-4 center text-center"><i class="icon-home"></i> <?php print $vOrganizacao['nome_organizacao']?></div>
                </div>
            </div>
        </footer>
        <?php print $this->headScript() ?>
    </body>
</html>
