<?php
/**
 *
 * Descrição:Classe navigation
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 20-Aug-2013
 *
 * @version 1.0.0
 *
 */
$html  = '<div class="navbar navbar-inverse navbar-fixed-top">';
$html .= ' <div class="container">';
$html .= '  <div class="navbar-header">';
$html .= '   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">';
$html .= '    <span class="icon-bar"></span>';
$html .= '    <span class="icon-bar"></span>';
$html .= '    <span class="icon-bar"></span>';
$html .= '   </button>';
$html .= '   <a class="navbar-brand" href="#">Grass</a>';
$html .= '   </div>';
$html .= '   <div class="collapse navbar-collapse">';

/**
 * @todo Desenvolver links do menu de acordo com o perfil do usuário logado 
 * e as definições de funcionalidades para o grupo 
 */

$html .= '<form class="navbar-form navbar-right" action="'.$this->url(array('controller' => 'auth','action'=>'logout')).'">
            <button type="submit" class="btn btn-success">Sair</button>
          </form>';
$html .= '</div>
       </div>
    </div>
</div>';
echo $html;