<?php
/**
 *
 * Descrição:sobre
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 22-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<div class="panel panel-info">
    <div class="panel-heading">Sobre</div>
    <div class="panel-body">
        <p>The lunatics is on the grass...</p>
    </div>
    <ul class="list-group">
        <li class="list-group-item"><i class="icon-linux"></i> <a href="http://www.nogsantos.com.br" target="_blank">www.nogsantos.com.br</a></li>
        <li class="list-group-item"><i class="icon-linkedin"></i> <a href="http://www.linkedin.com/in/nogsantos" target="_blank">Linkedin</a></li>
        <li class="list-group-item"><i class="icon-github-alt"></i> <a href="https://github.com/nogsantos" target="_blank">GitHub</a></li>
        <li class="list-group-item"><i class="icon-facebook"></i> <a href="https://www.facebook.com/nogsantos" target="_blank">Facebook</a></li>
        <li class="list-group-item"><i class="icon-instagram"></i> <a href="http://instagram.com/nogsantos" target="_blank">Instagram</a></li>
    </ul>
</div>