<div class="page-header">
    <h1><i class="icon-cogs icon-2x"></i> Ocorreu um erro no sistema <small>Desculpe-nos pelo inconveniente.</small></h1>
</div>
<div class="row">
    <h2><?php echo $this->message ?></h2>
</div>
<div class="row">
    <input type="button" class="btn btn-warning pull-right" value="Retornar a p&aacute;gina anterior" title="Retornar a P&acute;gina anterior" onclick="goBack()">
</div>
<script type="text/javascript" src="<?php print $this->baseUrl('/js/default.js')?>"></script>