begin;
CREATE OR REPLACE FUNCTION nvl(character varying, character varying) RETURNS character varying AS 
$$
/**
 * Substitui o valor do primeiro termo pelo segundo caso o primeiro valor esteja nulo.
 * Eschema Public
 *
 * @author Fabricio Nogueira
 * @since 14 AGO 2013
 */
    select case 
        when $1 is null 
        then $2 
        else $1 
    end
$$
LANGUAGE 'sql' VOLATILE;

commit;

Pessoa

CD_PESSOA	NUMBER(6,0)
NM_PESSOA	VARCHAR2(60 BYTE)
NM_LOGRADOURO	VARCHAR2(60 BYTE)
NR_CEP	NUMBER(8,0)
NR_TELEFONE1	VARCHAR2(10 BYTE)
NR_TELEFONE2	VARCHAR2(10 BYTE)
NR_TELEFONE3	VARCHAR2(10 BYTE)
NR_DDD1	VARCHAR2(4 BYTE)
NR_DDD2	VARCHAR2(4 BYTE)
NR_DDD3	VARCHAR2(4 BYTE)
NM_EMAIL	VARCHAR2(60 BYTE)
NM_PAGINAWWW	VARCHAR2(60 BYTE)
IN_TIPO_PESSOA	VARCHAR2(1 BYTE)
BAIR_CD_BAIRRO	NUMBER(5,0)
CID_CD_CIDADE	NUMBER(6,0)
CD_CORRESPONDENTE	NUMBER(6,0)
CD_PAIS	VARCHAR2(2 BYTE)
SG_UF	VARCHAR2(2 BYTE)
IN_TIPO_TELEFONE1	CHAR(1 BYTE)
IN_TIPO_TELEFONE2	CHAR(1 BYTE)
IN_TIPO_TELEFONE3	CHAR(1 BYTE)
NM_CAIXAPOSTAL	VARCHAR2(5 BYTE)
CH_COMP_LOGRAD	VARCHAR2(40 BYTE)
CH_NM_BAIRRO	VARCHAR2(60 BYTE)
CH_NM_CIDADE	VARCHAR2(60 BYTE)

pessoa fisica

IN_SEXO	CHAR(1 BYTE)
IN_ESTADO_CIVIL	VARCHAR2(2 BYTE)
NR_CARTEIRA_IDENTIDADE	VARCHAR2(25 BYTE)
SG_ORGAO_EXPEDIDOR_CI	VARCHAR2(15 BYTE)
DT_EXPEDICAO_CI	DATE
NM_MAE	VARCHAR2(60 BYTE)
NM_PAI	VARCHAR2(60 BYTE)
NR_DOCUMENTO_MILITAR	VARCHAR2(20 BYTE)
NR_SERIE_DOCUMENTO_MILITAR	VARCHAR2(3 BYTE)
NM_CATEGORIA_MILITAR	VARCHAR2(3 BYTE)
NR_REGIAO_MILITAR	NUMBER(2,0)
NR_TITULO_ELEITOR	VARCHAR2(13 BYTE)
NR_ZONA_TITULO_ELEITOR	VARCHAR2(3 BYTE)
NR_SECAO_TITULO_ELEITOR	VARCHAR2(4 BYTE)
DT_NASCIMENTO	DATE
NR_PASSAPORT	VARCHAR2(20 BYTE)
IN_TIPO_PASSAPORT	VARCHAR2(1 BYTE)
NM_ORGAO_EXPEDIDOR_PASSAPORT	VARCHAR2(20 BYTE)
DT_EXPEDICAO_PASSAPORT	DATE
DT_CONCESSAO_VISTO_PASSAPORT	DATE
DT_EXPIRACAO_VISTO_PASSAPORT	DATE
NR_SERIE_PASSAPORT	NUMBER(8,0)
DT_CHEGADA_BRASIL	DATE
NR_CPF	NUMBER(11,0)
IN_ESCOLARIDADE	VARCHAR2(2 BYTE)
PES_CD_PESSOA	NUMBER(6,0)
PAIS_CD_PAIS	VARCHAR2(2 BYTE)
CID_CD_CIDADE	NUMBER(6,0)
SG_UF_TITULO_ELEITOR	VARCHAR2(2 BYTE)
SG_UF_IDENTIDADE	VARCHAR2(2 BYTE)
CD_PAIS_PASSAPORTE	VARCHAR2(2 BYTE)
SG_UF_NASCIMENTO	VARCHAR2(2 BYTE)
TRA_CD_TRATAMENTO	NUMBER(2,0)
DS_TRATAMENTO	VARCHAR2(20 BYTE)
DT_EXPEDICAO_MILITAR	DATE
DT_EXPEDICAO_TITULO_ELEITOR	DATE
IN_COR	VARCHAR2(1 BYTE)
NM_TIPO_SANGUINEO	VARCHAR2(5 BYTE)
NM_CONJUGE	VARCHAR2(60 BYTE)
CD_CIDADE_TITULO_ELEITOR	NUMBER(6,0)
NM_ORGAO_EXPEDIDOR_MILITAR	VARCHAR2(30 BYTE)
NR_CARTEIRA_ESTRANGEIRO	VARCHAR2(20 BYTE)
CD_PAIS_NACIONALIDADE	VARCHAR2(2 BYTE)
ID_LATTES	VARCHAR2(30 BYTE)
IN_TIPO_NACIONALIDADE	CHAR(2 BYTE)
IN_NECESSIDADES_ESPECIAIS	VARCHAR2(3 BYTE)
NR_PIS_PASEP	VARCHAR2(11 BYTE)
CD_NECESSIDADES_ESPECIAIS	NUMBER(3,0)
IN_TIPO_PIS_PASEP	NUMBER(1,0)
CH_NM_CID_NASC	VARCHAR2(60 BYTE)
CERTIDAO_CIVIL	NUMBER(1,0)
TIPO_CERTIDAO_CIVIL	NUMBER(1,0)
NUM_TERMO_CERTIDAO	VARCHAR2(8 BYTE)
FOLHA_CERTIDAO_CIVIL	VARCHAR2(4 BYTE)
LIVRO_CERTIDAO_CIVIL	VARCHAR2(8 BYTE)
DT_EMISSAO_CERTIDAO	DATE
UF_CARTORIO_CERTIDAO	CHAR(2 BYTE)
MUNICIPIO_CARTORIO	NUMBER(7,0)
CD_CARTORIO	VARCHAR2(6 BYTE)
NUM_REGISTRO_CERTIDAO_NOVA	VARCHAR2(32 BYTE)

pessoa juridica

NR_CGC	VARCHAR2(14 BYTE)
NM_FANTASIA	VARCHAR2(60 BYTE)
PES_CD_PESSOA	NUMBER(6,0)
PJ_TP_CD_CODIGO	VARCHAR2(2 BYTE)
SG_SIGLA	VARCHAR2(20 BYTE)
PJCLASS_NR_CODIGO	NUMBER(3,0)
IN_CLASSIFICACAO	NUMBER(3,0)