<?php
/**
 *
 * Descrição: View Listagem de ações (actions) dos sistema.
 *
 * @author Fabricio Nogueira
 *
 * @since 21-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<div class="page-header">
    <h1>A&ccedil;&otilde;es <small>Listagem de a&ccedil;&otilde;es</small></h1>
</div>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex2-collapse">
            <span class="sr-only">Alterar Navega&ccedil;&atilde;o</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse navbar-ex2-collapse">
        <button type="button" class="btn btn-default navbar-btn" id="bt_novo_action" rel="<?php echo $this->url(array('controller' =>'administrativo','action'=>'action.form'))?>"><i class="icon-file-alt"></i> Nova Action</button>
        <button type="button" class="btn btn-default navbar-btn disabled" id="bt_excluir_action" rel="<?php echo $this->url(array('controller' =>'administrativo','action'=>'excluir.action'))?>"><i class="icon-remove"></i> Excluir Selecionado</button>
    </div>
</nav>
<?php if (count($this->menssagens)) : ?>
    <?php foreach ($this->menssagens as $menssagens) : ?>
        <?php print $menssagens; ?>
    <?php endforeach; ?>
<?php endif; ?>
