<?php
/**
 *
 * Descrição:Formulário Action
 *
 * @author Fabricio Nogueira
 *
 * @since 26-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<?php print $this->menu ?>
<div class="panel panel-default">
    <div class="panel-heading">Formul&aacute;rio A&ccedil;&otilde;es</div>
    <div class="panel-body">        
        <div class="row-fluid">
            <div class="alert alert-danger" style="display: none;"></div>
            <form id="formAction" role="form" action="<?php echo $this->url(array('controller' =>'action','action'=>'salvar.action'))?>" method="POST">
                <input type="hidden" name="id_controller" value="<?php print @$this->oAction->id_action ?>" />
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group" id="div_fk_controller">
                            <label class="control-label" for="fk_controller">Controler * <i class="icon-question-sign" id="helpControladorField"></i></label>
                            <div class="row" style="margin-left:0;">
                                <div class="form-control" id="fk_controller" name="fk_controller"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group" id="codigo_action">
                            <label class="control-label" for="codigo_action">C&oacute;digo da action <i class="icon-question-sign" id="helpCodigoActionField"></i></label>
                            <input type="text" class="form-control" maxlength="250" name="codigo_action" id="codigo_action" value="<?php print @$this->oAction->codigo_action ?>" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group" id="div_tipo_action">
                            <label class="control-label" for=".tipo-action">Tipo <i class="icon-question-sign" id="helpTipoField"></i></label>
                            <div class="row" style="margin-left: 0px;">
                                <div class="btn-group" data-toggle="buttons">
                                    <label id="tipo_action_botao" class="btn btn-primary bt-tipo-action active">
                                        <input type="radio" class="tipo-action" name="tipo_action" value="B" checked="checked" />Bot&atilde;o
                                    </label>
                                    <label id="tipo_action_formulario" class="btn btn-primary bt-tipo-action">
                                        <input type="radio" class="tipo-action" name="tipo_action" value="F" />Formul&aacute;rio
                                    </label>
                                    <label id="tipo_action_funcao" class="btn btn-primary bt-tipo-action">
                                        <input type="radio" class="tipo-action" name="tipo_action" value="U" />Fun&ccedil;&atilde;o
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group" id="div_tipo_menu">
                            <label class="control-label" for=".tipo-menu">Tipo Menu <i class="icon-question-sign" id="helpTipoMenuField"></i></label>
                            <div class="row" style="margin-left: 0px;">
                                <div class="btn-group" data-toggle="buttons">
                                    <label class="btn btn-primary active">
                                        <input type="radio" id="tipo_menu_listagem" class="tipo-menu" name="tipo_menu" checked="checked" value="L" />Listagem
                                    </label>
                                    <label class="btn btn-primary">
                                        <input type="radio" id="tipo_menu_formulario" class="tipo-menu" name="tipo_menu" value="F" />Formul&aacute;rio
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group" id="div_nome_action">
                            <label class="control-label" for="nome_action">Nome * <i class="icon-question-sign" id="helpNomeField"></i></label>
                            <input type="text" class="form-control" maxlength="100" name="nome_action" id="nome_action" value="<?php print @$this->oAction->nome_action ?>" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group" id="div_id_action">
                            <label class="control-label" for="id_action">C&oacute;digo identificador <code>tag &lt;id&gt; </code> * <i class="icon-question-sign" id="helpCodigoIdentificadorField"></i></label>
                            <input type="text" class="form-control" maxlength="50" name="id_action" id="id_action" value="<?php print @$this->oAction->id_action ?>" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group" id="div_rel_controller">
                            <label class="control-label" for="rel_controller">Controller <i class="icon-question-sign" id="helpNomeControladorField"></i></label>
                            <input type="text" class="form-control" maxlength="100" name="rel_controller" id="rel_controller" value="<?php print @$this->oAction->rel_controller ?>" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group" id="div_rel_action">
                            <label class="control-label" for="rel_action">Action <i class="icon-question-sign" id="helpNomeAcaoField"></i></label>
                            <input type="text" class="form-control" maxlength="100" name="rel_action" id="rel_action" value="<?php print @$this->oAction->rel_action ?>" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group" data-toggle="buttons">
                            <label id="tipo_action_botao" class="btn btn-default">
                                <input type="radio" class="btn-default" name="tipo_action" value="btn-default"/>Padrão
                            </label>
                            <label id="tipo_action_botao" class="btn btn-primary">
                                <input type="radio" class="btn-primary" name="tipo_action" value="btn-primary"/>Primário
                            </label>
                            <label id="tipo_action_botao" class="btn btn-success">
                                <input type="radio" class="btn-success" name="tipo_action" value="btn-success"/>Sucesso
                            </label>
                            <label id="tipo_action_botao" class="btn btn-info">
                                <input type="radio" class="btn-info" name="tipo_action" value="btn-info"/>Inf.
                            </label>
                            <label id="tipo_action_botao" class="btn btn-warning">
                                <input type="radio" class="btn-warning" name="tipo_action" value="btn-warning"/>Atenção
                            </label>
                            <label id="tipo_action_botao" class="btn btn-danger">
                                <input type="radio" class="btn-danger" name="tipo_action" value="btn-danger"/>Perigo
                            </label>
                        </div>
                        <label class="control-label" for="class_botao">
                            Outra
                            <div class="form-group">
                                <input type="text" class="form-control" maxlength="100" name="class_botao" id="class_botao" value="<?php print @$this->oAction->class_botao ?>" />
                            </div>
                        </label>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group" id="div_class_icone">
                            <label class="control-label" for="class_icone">Classe icone <i class="icon-question-sign" id="helpClasseIconeField"></i></label>
                            <input type="text" class="form-control" maxlength="100" name="class_icone" id="class_icone" value="<?php print @$this->oAction->class_icone ?>" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group" id="descricao_action">
                            <label class="control-label" for="descricao_action">Descri&ccedil;&atilde;o <i class="icon-question-sign" id="helpDescricaoField"></i></label>
                            <input type="text" class="form-control" maxlength="500" name="descricao_action" id="descricao_action" value="<?php print @$this->oAction->descricao_action ?>" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group" id="numero_ordem">
                            <label class="control-label" for="numero_ordem">Ordem <i class="icon-question-sign" id="helpOrdemField"></i></label>
                            <input type="text" class="form-control" maxlength="10" name="numero_ordem" id="numero_ordem" value="<?php print @$this->oAction->numero_ordem ?>" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<link type="text/css" rel="stylesheet" media="screen" href="<?php print $this->baseUrl('/magicsuggest/magicsuggest-1.3.1.css')?>">
<link type="text/css" rel="stylesheet" media="screen" href="<?php print $this->baseUrl('/css/forms.css')?>">
<script src="<?php print $this->baseUrl('/magicsuggest/magicsuggest-1.3.1.js')?>" type="text/javascript"></script>
<script src="<?php print $this->baseUrl('/js/numeros.js')?>" type="text/javascript"></script>
<script src="<?php print $this->baseUrl('/js/default-forms.js')?>" type="text/javascript"></script>
<script src="<?php print $this->baseUrl('/js/administrativo/action/action-form.js')?>" type="text/javascript"></script>
