<?php
/**
 *
 * Descrição:cad-pessoa-fisica
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 21-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex2-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="collapse navbar-collapse navbar-ex2-collapse">
        <button type="button" class="btn btn-default navbar-btn">Salvar</button>
        <button type="button" class="btn btn-default navbar-btn">Excluir</button>
        <button type="button" class="btn btn-default navbar-btn">Imprimir</button>
    </div>
</nav>
<div class="panel panel-default">
    <div class="panel-heading">Formul&aacute;rio M&oacute;dulo</div>
    <div class="panel-body">
        <div class="row-fluid">
            <form role="form">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox"> Check me out
                    </label>
                </div>
            </form>
        </div>
    </div>
</div>