<?php
/**
 *
 * Descrição:Cadastro de controller.
 *
 * @author Fabricio Nogueira
 *
 * @since 21-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<?php echo $this->layout()->navigationFormulario; ?>
<div class="panel panel-default">
    <div class="panel-heading">Formul&aacute;rio Controlador</div>
    <div class="panel-body">        
        <div class="row-fluid">
            <div class="alert alert-danger" style="display: none;"></div>
            <form id="formController" role="form" action="<?php echo $this->url(array('controller' =>'administrativo','action'=>'salvar.controller'))?>" method="POST">
                <input type="hidden" name="id_controller" value="<?php print $this->oController->id_controller ?>"  />
                <div class="form-group" id="div_codigo_controller">
                    <label class="control-label" for="codigo_controller">C&oacute;digo *</label>
                    <input type="text" class="form-control" maxlength="250" id="codigo_controller" name="codigo_controller" placeholder="C&oacute;digo" value="<?php print $this->oController->codigo_controller?>">
                </div>
                <div class="form-group" id="div_nome_controller">
                    <label class="control-label" for="nome_controller">Nome *</label>
                    <input type="text" class="form-control" maxlength="300" id="nome_controller" name="nome_controller" placeholder="Nome" value="<?php print $this->oController->nome_controller?>">
                </div>
                <div class="form-group" id="div_descricao_controller">
                    <label class="control-label" for="descricao_controller">Descri&ccedil;&atilde;o</label>
                    <input type="text" class="form-control" maxlength="500" id="descricao_controller" name="descricao_controller" placeholder="Descri&ccedil;&atilde;o" value="<?php print $this->oController->descricao_controller?>">
                </div>
                <div class="form-group" id="div_numero_ordem">
                    <label class="control-label" for="numero_ordem">Ordem</label>
                    <input type="text" class="form-control number-only" id="numero_ordem" name="numero_ordem" placeholder="Ordem" value="<?php print $this->oController->numero_ordem?>">
                </div>
                    <div class="form-group" id="div_data_bloqueio">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="data_bloqueio" id="data_bloqueio" <?php print $this->oController->data_bloqueio == "" ? 'checked="checked"' : $this->oController->id_controller != "" ? 'checked="checked"' : '' ?> > Ativo
                        </label>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php echo $this->headLink() ?>
<?php echo $this->headScript() ?>