<?php
/**
 *
 * Descrição:Cadastro de modulo.
 *
 *
 * @author Fabricio Nogueira
 *
 * @since 21-Aug-2013
 *
 * @version 1.0.0
 *
 */
?>
<?php echo $this->layout()->navigationFormulario; ?>
<div class="panel panel-default">
    <div class="panel-heading">Formul&aacute;rio M&oacute;dulo</div>
    <div class="panel-body">        
        <div class="row-fluid">
            <div class="alert alert-danger" style="display: none;"></div>
            <form id="formModulo" role="form" action="<?php echo $this->url(array('controller' =>'administrativo','action'=>'salvar.modulo'))?>" method="POST">
                <input type="hidden" name="id_modulo" value="<?php print $this->oModulo->id_modulo ?>"  />
                <div class="form-group" id="div_codigo_modulo">
                    <label class="control-label" for="codigo_modulo">C&oacute;digo *</label>
                    <input type="text" class="form-control" maxlength="250" id="codigo_modulo" name="codigo_modulo" placeholder="C&oacute;digo" value="<?php print $this->oModulo->codigo_modulo?>">
                </div>
                <div class="form-group" id="div_nome_modulo">
                    <label class="control-label" for="nome_modulo">Nome *</label>
                    <input type="text" class="form-control" maxlength="300" id="nome_modulo" name="nome_modulo" placeholder="Nome" value="<?php print $this->oModulo->nome_modulo?>">
                </div>
                <div class="form-group" id="div_descricao_modulo">
                    <label class="control-label" for="descricao_modulo">Descri&ccedil;&atilde;o</label>
                    <input type="text" class="form-control" maxlength="500" id="descricao_modulo" name="descricao_modulo" placeholder="Descri&ccedil;&atilde;o" value="<?php print $this->oModulo->descricao_modulo?>">
                </div>
                <div class="form-group" id="div_numero_ordem">
                    <label class="control-label" for="numero_ordem">Ordem</label>
                    <input type="text" class="form-control" id="numero_ordem" name="numero_ordem" placeholder="Ordem" value="<?php print $this->oModulo->numero_ordem?>">
                </div>
                <div class="form-group" id="div_data_bloqueio">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="data_bloqueio" id="data_bloqueio" <?php print $this->oModulo->data_bloqueio == "" ? 'checked="checked"' : $this->oModulo->id_modulo != "" ? 'checked="checked"' : '' ?> > Ativo
                        </label>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php echo $this->headScript() ?>