<?php
/**
 *
 * Descrição: View Listagem de perfil de acesso ao sistema.
 *
 * @author Fabricio Nogueira
 *
 * @since 09-Apr-2014
 *
 * @version 1.0.0
 *
 */
?>
<div class="container-fluid">
    <div class="page-header">
        <h1>Perfil <small>Listagem de perfis de acesso ao sistema</small></h1>
    </div>
    <?php print $this->menu?>
    <?php if (count($this->menssagens)) : ?>
        <?php foreach ($this->menssagens as $menssagens) : ?>
            <?php print $menssagens; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="row-fluid">
        <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered dataTable data-table" id="table-action" width="100%">
            <thead>
                <tr>
                    <th>Identificador</th>
                    <th>Nome</th>
                    <th>Descri&ccedil;&atilde;o</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->oAction as $action ) : ?>
                <tr class="table no-select" identificador="<?php print $action['id_action']?>" id="listagem_<?php print $action['id_action']?>" rel="<?php print $this->url(array('controller' =>'administrativo','action'=>'action.form','id_action'=>$action['id_action']))?>">
                    <td><?php print $action['controller'] ?></td>
                    <td><?php print $action['id_action'] ?></td>
                    <td><?php print $action['rel_controller'] ?></td>
                    <td><?php print $action['rel_action'] ?></td>
                    <td><?php print $action['nome_action'] ?></td>
                    <td><?php print $action['tipo_action'] ?></td>
                    <td><?php print $action['descricao_action'] ?></td>
                    <td class="text-center"><?php print $action['data_cadastro'] ?></td>
                    <td class="text-center"><?php print $action['data_bloqueio'] ?></td>
                </tr>
                <?php endforeach;?>
            </tbody>
        </table>
    </div>
</div>